version: "3"
services:
  backend:
    build: ./asistencia-backend
    command: npm start
    network_mode: "host"
    volumes:
      - ./asistencia-backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - stack.env
  frontend:
    build: ./asistencia-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - stack.env
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "6000:5432"
    env_file:
      - stack.env
volumes:
  postgres:
